"""
Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference is pentagonal and D = |Pk - Pj| is minimised; what is the value of D?
"""

from utils import pentagonal
pentagons = [pentagonal(n) for n in range(1,10000)]

for i, a in enumerate(pentagons):
    for b in pentagons[i:]:
        if a+b in pentagons and a-b in pentagons:
            print a, b, (a+b in pentagons), (a-b in pentagons)